#!/usr/bin/env python3
"""Generate iOS Localizable.strings (en, de) from the Android string resources.

iOS reuses the Android keys and wording so both apps share one terminology and
the "EN and DE together" rule has a single source. Run after changing
androidApp/src/main/res/values{,-de}/strings.xml:

    python3 scripts/android_strings_to_ios.py            # rewrite
    python3 scripts/android_strings_to_ios.py --check    # fail if stale
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "androidApp/src/main/res"
OUT = ROOT / "iosApp/CruxCoach/Resources"
LOCALES = {"en": "values", "de": "values-de"}
FORMAT = re.compile(r"%(\d+\$)?([-0-9.]*)([sdf%])")


def android_text(element) -> str:
    text = "".join(element.itertext())
    if text.startswith('"') and text.endswith('"') and len(text) >= 2:
        text = text[1:-1]
    text = text.replace("\\'", "'").replace('\\"', '"').replace("\\n", "\n").replace("\\t", "\t")
    text = text.replace("\\@", "@").replace("\\?", "?")
    # Android %s takes any object (Foundation: %@); %d becomes %ld because Swift Int is 64-bit.
    return FORMAT.sub(lambda m: "%%" if m.group(3) == "%" else
                      f"%{m.group(1) or ''}{m.group(2) if m.group(3) != 's' else ''}{ {'s': '@', 'd': 'ld'}.get(m.group(3), m.group(3)) }", text)


def ios_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")


def render(values_dir: str) -> str:
    entries = {}
    for xml in sorted((RES / values_dir).glob("strings*.xml")):
        for node in ET.parse(xml).getroot():
            name = node.get("name")
            if node.tag == "string" and name and node.get("translatable") != "false":
                entries[name] = android_text(node)
            elif node.tag == "plurals" and name:
                # Flattened: <name>.one / <name>.other; Swift picks by count (en/de only need these two).
                for item in node.findall("item"):
                    entries[f"{name}.{item.get('quantity')}"] = android_text(item)
    lines = ["/* GENERATED by scripts/android_strings_to_ios.py from the Android resources. Do not edit. */"]
    lines += [f'"{key}" = "{ios_escape(value)}";' for key, value in sorted(entries.items())]
    return "\n".join(lines) + "\n"


def main() -> int:
    stale = []
    for locale, values_dir in LOCALES.items():
        target = OUT / f"{locale}.lproj/Localizable.strings"
        content = render(values_dir)
        if "--check" in sys.argv:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                stale.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
    if stale:
        print("stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
