package com.cruxcoach.app.map

import com.cruxcoach.app.logbook.StateWatch
import com.cruxcoach.app.logbook.watchState
import com.cruxcoach.app.platform.KeyValueStore
import com.cruxcoach.data.repository.AccessType
import com.cruxcoach.data.repository.Adjustability
import com.cruxcoach.data.repository.BoardLocation
import com.cruxcoach.data.repository.BoardLocationRepository
import com.cruxcoach.domain.board.BoardBrand
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

enum class MapError { NONE, LOAD_FAILED }

/**
 * Two parallel datasets live here, exactly as in Android's `MapState`:
 *  - [unfilteredLocations]: every recorded board. It feeds the chip lists and
 *    the statistics, which describe ALL recorded boards regardless of filters.
 *  - [filteredLocations] / [filteredVenues]: what the map renders.
 */
data class MapState(
    val isLoading: Boolean = true,
    /** Canonical offline snapshot generated by cruxcoach-pages. */
    val canonicalLocations: List<BoardLocation> = emptyList(),
    val unfilteredLocations: List<BoardLocation> = emptyList(),
    val unfilteredVenues: List<MapVenue> = emptyList(),
    val filteredLocations: List<BoardLocation> = emptyList(),
    /** [filteredLocations] collapsed to one entry per physical venue — the pins. */
    val filteredVenues: List<MapVenue> = emptyList(),
    /** Statistics over the full dataset; Android's stats tab shows exactly this. */
    val unfilteredStats: MapStats = MapStats.Empty,
    /** Statistics over the filtered dataset. Kept for parity; the tab uses the unfiltered one. */
    val stats: MapStats = MapStats.Empty,
    val filters: MapFilters = MapFilters(),
    /** False when the user has no board configured — disables matchesMyBoard. */
    val canFilterByMyBoard: Boolean = false,
    val userBoardLayoutId: Int? = null,
    val userBoardSizeId: Int? = null,
    val userBoardBrand: BoardBrand? = null,
    val selectedVenueId: String? = null,
    val noLocationData: Boolean = false,
    val error: MapError = MapError.NONE,
)

/**
 * Port of Android `MapViewModel`. Merges the bundled cruxcoach-pages snapshot
 * with the synced `kilter_board_location` rows, applies [MapFilters] and keeps
 * the venue collapsing and the statistics in one recomputation.
 */
class MapPresenter(
    private val repository: BoardLocationRepository,
    private val pages: PagesBoardMapSource,
    keyValues: KeyValueStore,
    private val scope: CoroutineScope = CoroutineScope(SupervisorJob() + Dispatchers.Main),
    private val ioDispatcher: CoroutineDispatcher = Dispatchers.Default,
) {
    private val filterStore = MapFilterStore(keyValues)
    private val preferences = keyValues

    private val _state = MutableStateFlow(MapState())
    val state: StateFlow<MapState> = _state.asStateFlow()

    init {
        scope.launch { load() }
    }

    fun watch(onState: (MapState) -> Unit): StateWatch = scope.watchState(state, onState)

    /** Re-reads the board preferences and the synced rows; safe to call on every appearance. */
    fun refresh() {
        scope.launch { load() }
    }

    fun close() = scope.cancel()

    private suspend fun load() {
        try {
            val (snapshot, dynamic) = withContext(ioDispatcher) {
                pages.load() to repository.getAll()
            }
            val all = mergeCanonicalMapLocations(snapshot.locations, dynamic)
            _state.update {
                it.copy(
                    isLoading = false,
                    canonicalLocations = snapshot.locations,
                    unfilteredLocations = all,
                    unfilteredVenues = groupIntoVenues(all),
                    unfilteredStats = MapStats.from(all),
                    noLocationData = all.isEmpty(),
                    filters = filterStore.read(),
                    error = MapError.NONE,
                )
            }
            readBoardPreferences()
            recomputeFiltered()
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            // The exception message can carry cache paths; only the code crosses to the UI.
            _state.update { it.copy(isLoading = false, error = MapError.LOAD_FAILED) }
        }
    }

    private fun readBoardPreferences() {
        // Same keys, spellings and defaults as `SettingsStore` / Android's DataStore.
        val storedSize = preferences.getString(BOARD_PRODUCT_SIZE_ID)?.toIntOrNull()
        _state.update {
            it.copy(
                userBoardBrand = BoardBrand.fromWire(preferences.getString(BOARD_BRAND)),
                userBoardLayoutId = preferences.getString(BOARD_LAYOUT_ID)?.toIntOrNull()
                    ?: KILTER_ORIGINAL_LAYOUT,
                userBoardSizeId = storedSize,
                // Android reads this as "the product-size key was never written".
                canFilterByMyBoard = storedSize != null,
            )
        }
    }

    private fun recomputeFiltered() {
        val s = _state.value
        val effective = if (!s.canFilterByMyBoard) s.filters.copy(matchesMyBoard = false) else s.filters
        val filtered = effective.apply(
            locations = s.unfilteredLocations,
            userBoardLayoutId = s.userBoardLayoutId,
            userBoardSizeId = s.userBoardSizeId,
            userBoardBrand = s.userBoardBrand,
        )
        val venues = groupIntoVenues(filtered)
        _state.update {
            it.copy(
                filteredLocations = filtered,
                filteredVenues = venues,
                stats = MapStats.from(filtered),
                // A pin that no longer exists must not keep a detail sheet open.
                selectedVenueId = it.selectedVenueId?.takeIf { id -> venues.any { v -> v.id == id } },
            )
        }
    }

    private fun mutate(block: (MapFilters) -> MapFilters) {
        val next = block(_state.value.filters)
        filterStore.write(next)
        _state.update { it.copy(filters = next) }
        recomputeFiltered()
    }

    fun selectVenue(id: String?) {
        _state.update { it.copy(selectedVenueId = id?.takeIf { v -> v.isNotEmpty() }) }
    }

    fun toggleShowOriginal() = mutate { it.copy(showOriginal = !it.showOriginal) }

    fun toggleShowHomewalls() = mutate { it.copy(showHomewalls = !it.showHomewalls) }

    /** "All" layout chip: show both Original and Homewall families. */
    fun selectAllLayouts() = mutate { it.copy(showOriginal = true, showHomewalls = true) }

    fun toggleMatchesMyBoard() {
        if (!_state.value.canFilterByMyBoard) return
        mutate { it.copy(matchesMyBoard = !it.matchesMyBoard) }
    }

    fun toggleCountry(code: String) = mutate { it.copy(countries = it.countries.toggle(code)) }

    fun toggleAccessType(type: AccessType) = mutate { it.copy(accessTypes = it.accessTypes.toggle(type)) }

    fun toggleAdjustability(adj: Adjustability) =
        mutate { it.copy(adjustabilities = it.adjustabilities.toggle(adj)) }

    fun toggleSizeId(sizeId: Int) = mutate { it.copy(sizeIds = it.sizeIds.toggle(sizeId)) }

    fun toggleBrand(brand: BoardBrand) = mutate { it.copy(brands = it.brands.toggle(brand)) }

    /** "Other boards" chip: the whole map-only info-layer family set in one tap. */
    fun toggleOtherBrands() = mutate { filters ->
        val group = BoardBrand.INFO_LAYER.toSet()
        val next = if (group.all { it in filters.brands }) filters.brands - group else filters.brands + group
        filters.copy(brands = next)
    }

    /** "All" brand chip: clear the brand filter (empty = every brand). */
    fun selectAllBrands() = mutate { it.copy(brands = emptySet()) }

    fun toggleWellpassOnly() = mutate { it.copy(wellpassOnly = !it.wellpassOnly) }

    fun toggleMoonLayoutId(layoutId: Int) =
        mutate { it.copy(moonLayoutIds = it.moonLayoutIds.toggle(layoutId)) }

    fun toggleMoonLedState(state: MoonLedState) =
        mutate { it.copy(moonLedStates = it.moonLedStates.toggle(state)) }

    fun resetFilters() {
        filterStore.reset()
        _state.update { it.copy(filters = MapFilters()) }
        recomputeFiltered()
    }

    private fun <T> Set<T>.toggle(value: T): Set<T> = if (value in this) this - value else this + value

    companion object {
        private const val BOARD_BRAND = "board_brand"
        private const val BOARD_LAYOUT_ID = "board_layout_id"
        private const val BOARD_PRODUCT_SIZE_ID = "board_product_size_id"
    }
}
