package com.cruxcoach.domain.competition

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject

/**
 * The entry fee in the app, against the fixtures the website asserts on.
 *
 * Nothing here contacts a network and nothing here is payable: the fixture
 * invoice is structurally valid and deliberately unsigned, generated by
 * `tools/dev/fake-invoice.mjs`, and every receipt was signed by a test key.
 *
 * The cases that matter are the refusals. A zap receipt is an attestation by
 * whoever the payment endpoint named, so the only useful question is whether it
 * is the *right* attestation — and each way of being the wrong one has to be
 * caught separately, in this client exactly as in the other.
 */
class CompetitionLightningTest {

    private val fixture: JsonObject by lazy { CompetitionFixtures.read("vectors/zap.json") }
    private val lnurl: JsonObject get() = fixture["lnurl_response"]!!.jsonObject
    private val invoiceFixture: JsonObject get() = fixture["invoice"]!!.jsonObject
    private val feeMsat: Long get() = fixture.long("fee_msat")!!

    private val zapRequest: CompetitionEvent by lazy {
        CompetitionZap.eventFrom(fixture["zap_request"]!!.jsonObject)!!
    }

    private fun receipt(name: String): CompetitionEvent =
        CompetitionZap.eventFrom(fixture["rejected"]!!.jsonObject[name]!!.jsonObject)!!

    private val validReceipt: CompetitionEvent by lazy {
        CompetitionZap.eventFrom(fixture["valid_receipt"]!!.jsonObject)!!
    }

    /**
     * The app supplies Schnorr verification from Quartz; `:shared` has none and
     * must not gain one. Here the fixture itself is the authority on which
     * events were validly signed: everything in it was signed by a test key,
     * and the tampered cases are tampered by editing tags after signing, which
     * `idBinds` catches without any crypto at all.
     */
    private val signaturesHold: (CompetitionEvent) -> Boolean = { CompetitionZap.idBinds(it) }

    private val expected: CompetitionZap.Expected by lazy {
        CompetitionZap.Expected(
            providerPubkey = lnurl.str("nostrPubkey"),
            payerPubkey = zapRequest.pubkey,
            recipientPubkey = zapRequest.tagValue("p")!!,
            address = fixture.str("competition_address")!!,
            amountMsat = feeMsat,
            nonce = fixture.str("intent_nonce"),
        )
    }

    // ── BOLT11 ──

    @Test
    fun `a BOLT11 spec vector decodes to its documented fields`() {
        val invoice = "lnbc2500u1pvjluezpp5qqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqqqsyqcyq5rqwzqfqypq" +
            "dq5xysxxatsyp3k7enxv4jsxqzpuaztrnwngzn3kdzw5hydlzf03qdgm2hdq27cqv3agm2awhz5se903vru" +
            "atfhq77w3ls4evs3ch9zw97j25emudupq63nyw24cg27h2rspfj9srp"
        val decoded = CompetitionBolt11.decode(invoice)
        val ok = decoded as CompetitionBolt11.Result.Ok
        assertEquals("bc", ok.invoice.network)
        assertEquals(250_000_000L, ok.invoice.amountMsat)
        assertEquals(1496314658L, ok.invoice.timestamp)
        assertEquals(60, ok.invoice.expirySec)
        assertEquals("1 cup coffee", ok.invoice.description)
        assertEquals(
            "0001020304050607080900010203040506070809000102030405060708090102",
            ok.invoice.paymentHash,
        )
    }

    @Test
    fun `the amount in the prefix is read exactly, including pico`() {
        assertEquals(CompetitionBolt11.Hrp("bc", null), CompetitionBolt11.parseHrp("lnbc"))
        assertEquals(CompetitionBolt11.Hrp("bc", 2_000_000L), CompetitionBolt11.parseHrp("lnbc20u"))
        assertEquals(CompetitionBolt11.Hrp("bc", 100_000_000L), CompetitionBolt11.parseHrp("lnbc1m"))
        assertEquals(CompetitionBolt11.Hrp("bc", 700L), CompetitionBolt11.parseHrp("lnbc7n"))
        assertEquals(CompetitionBolt11.Hrp("bc", 100_000_000_000L), CompetitionBolt11.parseHrp("lnbc1"))
        assertEquals(CompetitionBolt11.Hrp("tb", 2_000_000L), CompetitionBolt11.parseHrp("lntb20u"))
        assertEquals(CompetitionBolt11.Hrp("bc", 1L), CompetitionBolt11.parseHrp("lnbc10p"))
        // A pico amount that is not a multiple of ten cannot be paid.
        assertNull(CompetitionBolt11.parseHrp("lnbc1p"))
        assertNull(CompetitionBolt11.parseHrp("lnbcXu"))
        assertNull(CompetitionBolt11.parseHrp("bc20u"))
    }

    @Test
    fun `the fixture invoice decodes to exactly what the fixture claims`() {
        val ok = CompetitionBolt11.decode(invoiceFixture.str("bolt11")!!) as CompetitionBolt11.Result.Ok
        assertEquals(invoiceFixture.long("amount_msat"), ok.invoice.amountMsat)
        assertEquals(invoiceFixture.long("timestamp"), ok.invoice.timestamp)
        assertEquals(invoiceFixture.long("expires_at"), ok.invoice.expiresAt)
        assertEquals(invoiceFixture.str("payment_hash"), ok.invoice.paymentHash)
        assertEquals(invoiceFixture.str("description_hash"), ok.invoice.descriptionHash)
    }

    @Test
    fun `expiry is reported rather than left for somebody to discover at the desk`() {
        val ok = CompetitionBolt11.decode(invoiceFixture.str("bolt11")!!) as CompetitionBolt11.Result.Ok
        val expiresAt = invoiceFixture.long("expires_at")!!
        assertFalse(ok.invoice.isExpired(expiresAt - 1))
        assertEquals(60L, ok.invoice.secondsLeft(expiresAt - 60))
        assertTrue(ok.invoice.isExpired(expiresAt))
        assertEquals(0L, ok.invoice.secondsLeft(expiresAt + 500))
    }

    @Test
    fun `anything that is not an invoice is refused, not half-read`() {
        for ((input, error) in listOf(
            "" to "empty",
            "not an invoice at all" to "not_bech32",
            "npub1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqshp52w2" to "not_an_invoice",
            "lnbc20u1qqqqqqqqqqqqqqqqqqqqr6alde" to "too_short",
        )) {
            val result = CompetitionBolt11.decode(input)
            assertEquals(error, (result as CompetitionBolt11.Result.Failed).error, input)
        }
    }

    @Test
    fun `the wallet URI is the one a phone hands to a lightning app`() {
        assertEquals("lightning:lnbc20u1abc", CompetitionBolt11.walletUri("LNBC20U1ABC"))
    }

    // ── LNURL ──

    @Test
    fun `a lightning address resolves to its well-known endpoint`() {
        val resolved = CompetitionLnurl.resolvePayEndpoint("kellerwand@example.org")
        val ok = resolved as CompetitionLnurl.Resolved.Ok
        assertEquals("https://example.org/.well-known/lnurlp/kellerwand", ok.endpoint.url)
        assertEquals("address", ok.endpoint.kind)
    }

    @Test
    fun `an endpoint that could be intercepted is refused, never downgraded`() {
        for ((value, error) in listOf(
            "" to "empty",
            "gym@somewhere" to "bad_domain",
            "gym@abcdefghijklmnop.onion" to "onion",
            "http://example.org/pay" to "not_https",
            "lnurl1qqqqq" to "bad_lnurl",
            "not a thing" to "unrecognised",
        )) {
            val result = CompetitionLnurl.resolvePayEndpoint(value)
            assertEquals(error, (result as CompetitionLnurl.Resolved.Failed).error, value)
        }
    }

    @Test
    fun `credentials in the authority are refused, because they read as the wrong host`() {
        // https://evil.example@bank.example resolves to evil.example and reads
        // to a person as bank.example.
        val result = CompetitionLnurl.resolvePayEndpoint("https://evil.example@bank.example/pay")
        assertEquals("bad_url", (result as CompetitionLnurl.Resolved.Failed).error)
    }

    @Test
    fun `a pay response is checked against what this competition charges`() {
        val ok = CompetitionLnurl.validatePayResponse(lnurl, feeMsat) as CompetitionLnurl.PayResult.Ok
        assertEquals(lnurl.str("callback"), ok.request.callback)
        assertTrue(ok.request.allowsNostr)
        assertEquals(lnurl.str("nostrPubkey"), ok.request.nostrPubkey)

        assertEquals(
            "below_minimum",
            (CompetitionLnurl.validatePayResponse(lnurl, 100) as CompetitionLnurl.PayResult.Failed).error,
        )
        assertEquals(
            "above_maximum",
            (CompetitionLnurl.validatePayResponse(lnurl, 999_999_999) as CompetitionLnurl.PayResult.Failed).error,
        )
    }

    @Test
    fun `a provider that cannot zap is reported as unverifiable, not as fine`() {
        val noNostr = JsonObject(lnurl.toMutableMap().apply {
            put("allowsNostr", kotlinx.serialization.json.JsonPrimitive(false))
        })
        val ok = CompetitionLnurl.validatePayResponse(noNostr, feeMsat) as CompetitionLnurl.PayResult.Ok
        assertFalse(ok.request.allowsNostr, "no receipt can be verified against this endpoint")
        assertNull(ok.request.nostrPubkey)
    }

    @Test
    fun `a malformed pay response is refused case by case`() {
        fun withField(key: String, value: kotlinx.serialization.json.JsonElement?): JsonObject =
            JsonObject(lnurl.toMutableMap().apply { if (value == null) remove(key) else put(key, value) })

        val prim = { text: String -> kotlinx.serialization.json.JsonPrimitive(text) }
        val cases = listOf(
            withField("tag", prim("withdrawRequest")) to "not_a_pay_request",
            withField("callback", prim("http://example.org/cb")) to "bad_callback",
            withField("minSendable", kotlinx.serialization.json.JsonPrimitive(0)) to "bad_limits",
            withField("maxSendable", kotlinx.serialization.json.JsonPrimitive(1)) to "bad_limits",
            withField("metadata", null) to "no_metadata",
            withField("metadata", prim("{\"not\":\"an array\"}")) to "bad_metadata",
            withField("status", prim("ERROR")) to "provider_error",
        )
        for ((response, error) in cases) {
            val result = CompetitionLnurl.validatePayResponse(response, feeMsat)
            assertEquals(error, (result as CompetitionLnurl.PayResult.Failed).error, error)
        }
        assertEquals(
            "not_json",
            (CompetitionLnurl.validatePayResponse(null, feeMsat) as CompetitionLnurl.PayResult.Failed).error,
        )
    }

    @Test
    fun `the invoice request carries the amount and the zap request`() {
        val url = CompetitionLnurl.invoiceUrl(lnurl.str("callback")!!, feeMsat, "{\"kind\":9734}")
        assertTrue(url.contains("amount=$feeMsat"), url)
        assertTrue(url.contains("nostr=%7B%22kind%22%3A9734%7D"), url)
        // A callback that already has a query keeps it.
        assertTrue(
            CompetitionLnurl.invoiceUrl("https://x.example/cb?id=1", 1000).contains("?id=1&amount=1000"),
        )
    }

    @Test
    fun `an invoice for a different amount is refused, not shown with a warning`() {
        val response = JsonObject(
            mapOf("pr" to kotlinx.serialization.json.JsonPrimitive(invoiceFixture.str("bolt11")!!)),
        )
        assertTrue(CompetitionLnurl.validateInvoiceResponse(response, feeMsat) is CompetitionLnurl.InvoiceResult.Ok)

        val wrong = CompetitionLnurl.validateInvoiceResponse(response, feeMsat * 2)
            as CompetitionLnurl.InvoiceResult.Failed
        assertEquals("wrong_amount", wrong.error)
        assertEquals(feeMsat, wrong.invoiceMsat)

        assertEquals(
            "no_invoice",
            (CompetitionLnurl.validateInvoiceResponse(JsonObject(emptyMap()), 1)
                as CompetitionLnurl.InvoiceResult.Failed).error,
        )
    }

    // ── zaps ──

    @Test
    fun `a zap request names the competition, the amount and the registration`() {
        val tags = CompetitionZap.buildZapRequestTags(
            recipientPubkey = expected.recipientPubkey,
            address = expected.address,
            amountMsat = expected.amountMsat,
            relays = listOf("wss://relay.example.invalid"),
            nonce = expected.nonce!!,
        )
        assertEquals(zapRequest.tags, tags)
    }

    @Test
    fun `the fixture receipt verifies against this competition`() {
        val verdict = CompetitionZap.verifyReceipt(validReceipt, expected, signaturesHold)
        val ok = verdict as CompetitionZap.Verdict.Ok
        assertEquals(feeMsat, ok.amountMsat)
        assertFalse(ok.weaklyBound, "the fixture invoice carries a description hash")
    }

    @Test
    fun `every way of being the wrong receipt is caught, exactly as on the website`() {
        val cases = listOf(
            "signed_by_the_wrong_key" to "wrong_signer",
            "references_another_competition" to "wrong_competition",
            "attests_a_smaller_amount" to "wrong_amount",
            "attests_somebody_elses_payment" to "wrong_payer",
            "pays_a_different_registration" to "wrong_registration",
            "description_signature_does_not_hold" to "bad_request_signature",
        )
        for ((name, error) in cases) {
            val verdict = CompetitionZap.verifyReceipt(receipt(name), expected, signaturesHold)
            assertEquals(error, (verdict as CompetitionZap.Verdict.Failed).error, name)
        }
    }

    @Test
    fun `a receipt cannot be verified at all when the endpoint named no key`() {
        val verdict = CompetitionZap.verifyReceipt(
            validReceipt,
            expected.copy(providerPubkey = null),
            signaturesHold,
        )
        assertEquals("no_provider_key", (verdict as CompetitionZap.Verdict.Failed).error)
    }

    @Test
    fun `a tampered receipt fails on its binding, not on its contents`() {
        val tampered = validReceipt.copy(createdAt = validReceipt.createdAt + 1)
        val verdict = CompetitionZap.verifyReceipt(tampered, expected, signaturesHold)
        assertEquals("bad_signature", (verdict as CompetitionZap.Verdict.Failed).error)
    }

    @Test
    fun `a caller that cannot check signatures fails rather than waving it through`() {
        val verdict = CompetitionZap.verifyReceipt(validReceipt, expected) { false }
        assertEquals("bad_signature", (verdict as CompetitionZap.Verdict.Failed).error)
    }

    @Test
    fun `a receipt from outside its window is refused`() {
        val at = validReceipt.createdAt
        assertEquals(
            "receipt_too_early",
            (CompetitionZap.verifyReceipt(validReceipt, expected.copy(notBefore = at + 1), signaturesHold)
                as CompetitionZap.Verdict.Failed).error,
        )
        assertEquals(
            "receipt_too_late",
            (CompetitionZap.verifyReceipt(validReceipt, expected.copy(notAfter = at - 1), signaturesHold)
                as CompetitionZap.Verdict.Failed).error,
        )
        assertTrue(
            CompetitionZap.verifyReceipt(
                validReceipt,
                expected.copy(notBefore = at - 10, notAfter = at + 10),
                signaturesHold,
            ) is CompetitionZap.Verdict.Ok,
        )
    }

    @Test
    fun `the id of every fixture event binds its own body`() {
        // If this ever fails, the fixtures were edited by hand rather than
        // regenerated, and every verification result above is meaningless.
        assertTrue(CompetitionZap.idBinds(zapRequest), "zap request")
        assertTrue(CompetitionZap.idBinds(validReceipt), "valid receipt")
        for (name in fixture["rejected"]!!.jsonObject.keys) {
            val event = receipt(name)
            if (name == "description_signature_does_not_hold") continue
            assertTrue(CompetitionZap.idBinds(event), "$name should be a validly formed event")
        }
    }

    @Test
    fun `nothing in the fixtures is payable`() {
        assertTrue(
            invoiceFixture.str("note")!!.lowercase().contains("unsigned"),
            "the fixture must say plainly that its invoice is not real",
        )
    }
}
